version: '3.3'

services:
        bck-end:
          build: ./back-end
          ports:
            - 5000:8080
          tty: true
          stdin_open: true

        frt-end:
          build: ./front-end
          ports:
            - 80:8080