version: '3.3'

services:
        bck-end:
          build: ./back-end
          ports:
            - 5000:8080
          tty: true
          stdin_open: true
          environment:
            - PROD=1
          volumes:
            - ./:/home/api/DialogFlowAutoCorrect

        frt-end:
          build: ./front-end
          environment:
            - PROD=0
          ports:
            - 80:8080
          volumes:
            - ./:/home/front/DialogFlowAutoCorrect